### ISSUE TITLE
Client ip logged but unknown

### ISSUE THREAD

**Issue by ecamellini** [buildo/wiro#152]
In debug mode, the logged client IP is `unknown`:

![image](https://user-images.githubusercontent.com/6418684/62870716-61419c80-bd1a-11e9-8ae8-e83484adb6cf.png)

How to reproduce:
1. Set log level to `debug`
2. Wait for wiro server to receive a request
3. Check the logged client IP

Expected:
The client IP is correctly displayed

Actual:
The client IP is logged as `unknown`

**Comment by calippo** [comment]
@ecamellini are you testing this locally? In localhost this is the expected behavior.

Wiro reads the IP from `X-Forwarded-For` http header. I expect this to be populated by Nginx.
Please close the issue or test it behind a proper proxy (I'm not going to document this since we're deprecating wiro soon).

**Comment by ecamellini** [comment]
Let's just close this
